name = "CompositionalNetworks"
uuid = "4b67e4b5-442d-4ef5-b760-3f5df3a57537"
authors = ["Jean-Fran√ßois Baffier"]
version = "0.0.1"

[deps]
Evolutionary = "86b6b26d-c046-49b6-aa0b-5f0f74682bd6"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
